name: Deploy to Server-3
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install SSH client
        run: sudo apt-get install openssh-client -y
      
      - name: Create known_hosts file
        run: mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
      
      - name: Add host key to known_hosts
        run: ssh-keyscan -p 2222 181.191.104.4 >> ~/.ssh/known_hosts
      
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
      - name: Test SSH connection
        run: ssh -T -p 2222 root@181.191.104.4

      - name: Deploy code to server
        run: ssh -p 2222 -i ~/.ssh/id_rsa root@181.191.104.4 "bash -s" < ./deploy.sh
