name: Deploy to Server-2
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install ssh
        run: sudo apt-get install openssh-client
        
      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add host key
        run: ssh-keyscan -p 2222 181.191.104.4 >> ~/.ssh/known_hosts
        
      - name: Test SSH connection
        run: ssh -T -p 2222 root@181.191.104.4

      - name: Deploy code to server
        run: ssh -p 2222 -i ~/.ssh/id_rsa root@181.191.104.4 -v "bash -s" < ./deploy.sh
