name: Deploy to Production
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
      - name: SSH into production server
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: 181.191.104.1
          ssh-username: t2web
      - name: Deploy code to production
        run: ssh -o "StrictHostKeyChecking no" t2web@181.191.104.1 "cd /opt/testerepo && git pull origin master && exit"
